# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0002_auto_20181020_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='health_dept',
            field=models.IntegerField(default='0700505221', max_length=20),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_dept',
            field=models.IntegerField(default='0722445233', max_length=20),
        ),
    ]
