# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0003_auto_20181021_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='health_dept',
            field=models.IntegerField(default='0700505221'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='police_dept',
            field=models.IntegerField(default='0722445233'),
        ),
    ]
