# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0005_auto_20181021_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join',
            old_name='hood_id',
            new_name='hood',
        ),
    ]
